/usr/local/bin/dcli -l root -g /root/cell_group -f ~/cell_addtl_stats.scl
/usr/local/bin/dcli -l root -g /root/cell_group -f ~/cell_cg_iops.scl
/usr/local/bin/dcli -l root -g /root/cell_group -f ~/cell_cg_latency.scl
/usr/local/bin/dcli -l root -g /root/cell_group -f ~/cell_cg_mbs.scl
/usr/local/bin/dcli -l root -g /root/cell_group -f ~/cell_db_iops.scl
/usr/local/bin/dcli -l root -g /root/cell_group -f ~/cell_db_latency.scl
/usr/local/bin/dcli -l root -g /root/cell_group -f ~/cell_db_mbs.scl
/usr/local/bin/dcli -l root -g /root/cell_group -f ~/cell_flash_destage.scl
/usr/local/bin/dcli -l root -g /root/cell_group -f ~/cell_flash_space.scl
/usr/local/bin/dcli -l root -g /root/cell_group -f ~/cell_flashlog_outliers.scl
/usr/local/bin/dcli -l root -g /root/cell_group -f ~/cell_flashlog_skip.scl
/usr/local/bin/dcli -l root -g /root/cell_group -f ~/cell_iops.scl
/usr/local/bin/dcli -l root -g /root/cell_group -f ~/cell_latency.scl
/usr/local/bin/dcli -l root -g /root/cell_group -f ~/cell_mbs.scl
